const chess = require('./pages/api/minichess/leahchess')
const board = new chess.Board(5)
console.log(board.toString())
console.log(board.moves())
board.play('c2c3')
console.log(board.toString())
console.log(board.moves())